import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DirectionProvider from "./DirectionProvider";
import { Providers } from "./providers";
import ThemeWrapper from "@/components/atoms/ThemeWrapper/ThemeWrapper";
import QueryProviders from "./QueryProviders";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SU App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const language = typeof window !== "undefined"
    ? localStorage.getItem("i18nextLng") || "en"
    : "en";

  return (
    <html lang={language} dir={language === "ar" ? "rtl" : "ltr"}>
      <body>
        <QueryProviders>
        <DirectionProvider />
        
        <Providers>
          <ThemeWrapper>
        {children}
        </ThemeWrapper>
        </Providers>
        </QueryProviders>
        <div id="modal"/>
      </body>
    </html>
  );
}

